### PR TITLE
Move VEU code to libshveu

### PR DESCRIPTION
**Pull request by pedwo**
Hi Damian,

All working now... it turned out to be a much bigger job than I originally thought due to the way the code used to wait for either JPU or VEU events.

Best regards
Phil

### CODE REVIEW

**Comment by dhobsong** [comment]
Hi Phil,

Do we need to add the UIOMux and shveu dependencies ($(UIOMUX_LIBS)) into the test programs Makefile.am as well? I can't seem to compile without them.  Perhaps something odd with my system configuration.  I'm not sure, but shouldn't this kind of recursive dependency be handled by libtool?

**Comment by pedwo** [comment]
libtool should handle this, and I didn't see this problem :) Maybe some file has been left over between builds?
Phil

**Comment by dhobsong** [comment]
Hi Phil,
On 2011/08/22 15:29, pedwo wrote:

> > Do we need to add the UIOMux and shveu dependencies ($(UIOMUX_LIBS)) into the test programs Makefile.am as well? I can't seem to compile without
> > them.  Perhaps something odd with my system configuration.  I'm not sure, but shouldn't this kind of recursive dependency be handled by libtool?
> 
> libtool should handle this, and I didn't see this problem :) Maybe some file has been left over between builds?
> Phil
> 
> I'll double-check this with a completely fresh repo and hopefully it
> goes away.  I'm also using a bit of an older chroot environment, so
> there may be some issues there.

On a different point however, from patch "Replace direct access to VEU
with calls to libshveu library"
-      if (!context->mode420) {
-        // TODO modes other than 420 are not supported
-        return -1;
-      }

Do we no longer support colour conversions from NV16?  Does this involve
more than just setting veu.src.format to REN_NV16?

Damian

## 

Damian Hobson-Garcia
IGEL Co.,Ltd
http://www.igel.co.jp

**Comment by pedwo** [comment]
Ah, I missed that. Yes, libshveu supports NV16 by just changing veu.src.format. I'll fix that...
Anything else before I send a new pull request?

**Comment by dhobsong** [comment]
Nothing else so far, but I haven't finished looking through all of it
yet.  If you don't mind, I'll get back to you on that by the end of
the day today.

On 2011/08/22 16:10, pedwo wrote:

> Ah, I missed that. Yes, libshveu supports NV16 by just changing veu.src.format. I'll fix that...
> Anything else before I send a new pull request?

## 

Damian Hobson-Garcia
IGEL Co.,Ltd
http://www.igel.co.jp

**Comment by pedwo** [comment]
No problem!

**Comment by dhobsong** [comment]
Hi Phil,

On 2011/08/22 16:25, pedwo wrote:

> No problem!
> 
> Nothing else has really struck me as posing any problems so far.  I've
> started merging in the UIOMux support that I was working on.  I'll
> probably have to push either the JPU or VEU handing into a different
> thread if I'm going to use uiomux_sleep() alongside shveu_wait().
> I'll let you know if anything else crops up along the way.

One more thing. Do you recall a while back that I was saying that I saw
some strange behaviour with shveu when the controlling process was
killed while the VEU was processing data?
It seemed at the time that when the process is killed or dies
unexpectedly, the VEU never seems to recover even though shveu performs
a soft reset on startup.  Have you seen anything like this?

Thanks,
Damian

## 

Damian Hobson-Garcia
IGEL Co.,Ltd
http://www.igel.co.jp

**Comment by pedwo** [comment]
> Nothing else has really struck me as posing any problems so far.  I've
> started merging in the UIOMux support that I was working on.  I'll
> probably have to push either the JPU or VEU handing into a different
> thread if I'm going to use uiomux_sleep() alongside shveu_wait().
> I'll let you know if anything else crops up along the way.

These patches already split waiting for the JPU & VEU, so I would have thought you can directly modify the wait_and_process_jpu function to call
uiomux_sleep? The two are run synchronously as there are only two line buffers.

> One more thing. Do you recall a while back that I was saying that I saw
> some strange behaviour with shveu when the controlling process was
> killed while the VEU was processing data?
> It seemed at the time that when the process is killed or dies
> unexpectedly, the VEU never seems to recover even though shveu performs
> a soft reset on startup.  Have you seen anything like this?

I can't recall seeing this. A while back, there was an issue with libshveu getting more IRQs than it should (which looked like the VEU running when it
should have been reset), but this was due to a bug in UIOMux when using multiple instances. However, I have seen that the HW is a bit sensitive and
can't recover from bad sequences. No idea what causes this...

Best regards
Phil

**Comment by dhobsong** [comment]
Hi Phil,
On 2011/08/22 19:13, pedwo wrote:

> > Nothing else has really struck me as posing any problems so far.  I've
> > started merging in the UIOMux support that I was working on.  I'll
> > probably have to push either the JPU or VEU handing into a different
> > thread if I'm going to use uiomux_sleep() alongside shveu_wait().
> > I'll let you know if anything else crops up along the way.
> 
> These patches already split waiting for the JPU & VEU, so I would have thought you can directly modify the wait_and_process_jpu function to call
> uiomux_sleep? The two are run synchronously as there are only two line buffers.
> You're right.  I was originally thinking that there might be some
> problem relating to the timing of the UIO device interrupt enable, but
> it seems ok to just enable the UIO interrupt immediately before we sleep.
> 
> > One more thing. Do you recall a while back that I was saying that I saw
> > some strange behaviour with shveu when the controlling process was
> > killed while the VEU was processing data?
> > It seemed at the time that when the process is killed or dies
> > unexpectedly, the VEU never seems to recover even though shveu performs
> > a soft reset on startup.  Have you seen anything like this?
> 
> I can't recall seeing this. A while back, there was an issue with libshveu getting more IRQs than it should (which looked like the VEU running when it
> should have been reset), but this was due to a bug in UIOMux when using multiple instances. However, I have seen that the HW is a bit sensitive and
> can't recover from bad sequences. No idea what causes this...

I think that especially using bundle mode, if we break the process
early, the VEU will still be in operation, waiting for the next
VESTR.VE to be set.  I'm poking into this now and I'll let you know if I
find anything else.

Damian

**Comment by pedwo** [comment]
> I think that especially using bundle mode, if we break the process
> early, the VEU will still be in operation, waiting for the next
> VESTR.VE to be set.  I'm poking into this now and I'll let you know if I
> find anything else.

Ah, the HW manual does say that writing 0x100 to VBSRR can stop the VEU from working if it's in the middle of processing. The correct thing is set
VESTR.VE=0. I'll try this to see if I can reproduce the problem and if this fixes it.

Phil

**Comment by pedwo** [comment]
I've pushed a change to libshveu that should fix the VEU reset issue. let me know if that solves your VEU bundle mode problems.

**Comment by dhobsong** [comment]
Hi Phil,

On Wed, 24 Aug 2011, pedwo wrote:

> I've pushed a change to libshveu that should fix the VEU reset issue. let me know if that solves your VEU bundle mode problems.
> 
> Ok will do.  On another note, I think that I found a bug in the libshveu 
> support for libshjpeg.

In shjpeg_veu.c,

int shjpeg_veu_init(shjpeg_internal_t \* data, shjpeg_veu_t \* veu)
{
         if (shveu_setup(data->veu, &veu->src, &veu->dst, SHVEU_NO_ROT) != 
0) {
                 fprintf(stderr, "libshjpeg: %s: ERROR in shveu_setup!\n", 
**func**);
                 return 1;
         }
         /\* Set color conversion to BT601, full range data */
         shveu_set_color_conversion(data->veu, 0, 1);

```
return 0;
```

}

I believe that the colour conversion setting should come before the 
shveu_setup call.

Damian

**Comment by pedwo** [comment]
> I believe that the colour conversion setting should come before the
> shveu_setup call.
> Yes, you are right! I'll fix that.
> Thanks

**Comment by dhobsong** [comment]
Hi Phil,

I tried out the libshveu update.  Seems to work great on my previously
failing test.

Thanks,
Damian

On 2011/08/24 16:27, pedwo wrote:

> I've pushed a change to libshveu that should fix the VEU reset issue. let me know if that solves your VEU bundle mode problems.

## 

Damian Hobson-Garcia
IGEL Co.,Ltd
http://www.igel.co.jp

**Comment by dhobsong** [comment]
Hi Phil,

I haven't discovered any other issues with the libshveu support. Everything seems to be working well and fits in nicely with the UIOMux support I've been adding.  I believe you mentioned that you were going to submit another pull request for those two outstanding issues (NV16 and the colour mode setting)
Whenever you're ready with that I can merge it in.

Thanks again,
Damian

**Comment by pedwo** [comment]
> I haven't discovered any other issues with the libshveu support. 
> Everything seems to be working well and fits in nicely with the UIOMux 
> support I've been adding.  I believe you mentioned that you were going to 
> submit another pull request for those two outstanding issues (NV16 and the 
> colour mode setting)
> Whenever you're ready with that I can merge it in.
> Great, I'll try to do that today.
> Phil

**Comment by dhobsong** [comment]
On 2011/08/26 17:49, pedwo wrote:

> > I haven't discovered any other issues with the libshveu support. 
> > Everything seems to be working well and fits in nicely with the UIOMux 
> > support I've been adding.  I believe you mentioned that you were going to 
> > submit another pull request for those two outstanding issues (NV16 and the 
> > colour mode setting)
> > Oooh, actaully told a bit of a fib here.  There was one other thing that
> > I forgot about.  I had some trouble decoding files where the height was
> > not a multiple of 16.  Seems the INS11/INS12 interrupts only trigger
> > when a multiple of the 16 (though I suspect that this is really the PU
> > (processing unit) specified in JIFECNT) is transferred.  The last
> > transfer still needs to be done if the height doesn't line up.
> > If it doesn't line up the VEU sits in busy mode waiting for the last
> > bundle which never comes.  This also means the the uiomux_unlock is
> > never called, and you will deadlock if you try to run another VEU
> > operation in the same process.

With the attached patch things seemed to work.

> > Whenever you're ready with that I can merge it in.
> > Great, I'll try to do that today.
> > Phil
> 
> Damian
> From ac8b8a4c46a2c7bc1249810078d05d4bb318fdb1 Mon Sep 17 00:00:00 2001
> From: Damian Hobson-Garcia dhobsong@igel.co.jp
> Date: Fri, 26 Aug 2011 14:20:25 +0900
> Subject: [PATCH] Process last line buffer on decode when image height is not a mutliple of 16

If the image height is not a multiple of 16, the JPU does not assert
either INS11 or INS12 for the last buffer.  Force the last buffer processing

## when we get an INS10.

 src/shjpeg_jpu.c |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)

diff --git a/src/shjpeg_jpu.c b/src/shjpeg_jpu.c
index 5987921..d284125 100644
--- a/src/shjpeg_jpu.c
+++ b/src/shjpeg_jpu.c
@@ -114,6 +114,7 @@ process_jpu_ints(int ints, shjpeg_context_t *context,
        data->jpeg_end = 1;
        D_INFO("libshjpeg: xfer done");
        *done = 1;
- ```
    ints |= JPU_JINTS_INS12_LINEBUF1;
  ```
  
  }
  
  ## /\* Line buffer processing complete */
  
  1.7.1

**Pull request closed without merging**
